baseURL: ""
languageCode: "en-us"
title: "lilbitclassic"
theme: "aerial"

params: 
  name: "Elizabeth King"
  about: "making and breaking code one line at a time"
  social: 
    - link: "https://github.com/eliz-king"
      icon: "github"
      medium: "github"
    - link: "https://www.linkedin.com/in/elizking-dev/"
      icon: "linkedin"
      medium: "linkedin" 
    - link: "https://www.facebook.com/elizabeth.king.7315"
      icon: "facebook"
      medium: "facebook"
    - link: ""
      icon: "envelope-o"
      medium: "email"
  copyright: "King 2020"

deployment:
  targets: 
    - name: "home"
      url: "s3://home.lilbitclassic.com?region=us-west-2"

